### ISSUE TITLE
Undefined identifier MemoryChecked.

### ISSUE THREAD

**Issue by Fereter** [HoShiMin/Avanguard#7]
If enabled options `FEATURE_THREADS_FILTER`, `FEATURE_MEMORY_FILTER` and disabled option `FEATURE_DLL_FILTER` then during compilation there is an undefined identifier `MemoryChecked` at line 150 in file ThreadsFilter.cpp. The solution can be to replace this line by 
>`if (!MemoryFilter::IsMemoryKnown(EntryPoint)) {`

**Comment by HoShiMin** [comment]
Accepted, will be fixed in the next update

**Comment by HoShiMin** [comment]
Fixed
